const model = {
    Acura: ['ILX', 'TLX', 'RLX', 'CDX', 'RDX', 'MDX'],
    AlfaRomeo: ['Giulia', 'Stelvio', 'Tonale'],
    AstonMartin: ['DBX', 'DBS Superleggera', 'Vantage' ,'DB11'],
    Audi: ['S', 'TTS', 'SQ', 'RS', 'R', 'Q', 'A', 'TT'],
    AZLK: ['Москвич-433', 'Москвич-412', 'Москвич-427', 'Москвич-434'],
    Bentley: ['Continental GT', 'New Flying Spur', 'Flying Spur Speed', 'Bentayga', 'Bentayga Hybrid'],
    BMW: ['I', 'IX', 'M', 'X', 'XM', 'Z'],
    Briliance: ['V', 'H', 'M', 'Dolphin'],
    BYD: ['Destroyer 05', 'Seal', 'Han EV', 'Song', 'Tang 2', 'Tang EV600'],
    Cadillac: ['XT', 'Escalade', 'CT', 'CT-V', 'Lyriq', 'ATS', 'BLS', 'SRX', 'STC-V'],
    Changan: ['CS95', 'CS85COUPE', 'UNI', 'CS55 ', 'CS75FL'],
    Chery: ['Tiggo 2', 'Tiggo 3', 'Tiggo 4', 'Tiggo 7', 'Tiggo 8'],
    Chevrolet: ['Aveo', 'Blazer', 'Bolt', 'Camaro', 'Captiva', 'Cobalt', 'Colorado', 'Corbette'],
    Chrysler: ['180', '200', '300', 'Aspen', 'Cirrus'],
    Citroen: ['C4X', 'C3', 'C5'],
    Daewoo: ['Alpheon', 'Arcadia', 'Chairman', 'Damas', 'Espero.', 'Evanda', 'G2X', 'Gentra'],
    Daihatsu: ['Altis', 'Applause', 'Atrai', 'Ayla', 'Be-Go', 'Boon', 'Boon Luminas', 'Cast'],
    Datsun: ['GO', 'GO+', 'redi-GO', 'Cross'],
    Dodge: ['Challenger', 'Charger', 'Durango', 'Grand Caravan', 'Journey'],
    DongFeng: ['AX4', 'AX7', 'AX7 Pro', 'Joyear', 'Junfeng', 'S560', 'SUV5', 'X7', 'Yixuan', 'Yixuan EV'],
    EXEED: ['TXL', 'LX', 'TX', 'e-QM5'],
    FAW: ['Bestune T33', 'Bestune T77', 'Bestune T99', 'Jilin'],
    Fiat: ['500', '500X', '500L', 'Panda'],
    Ford: ['Mustang', 'Fusion', 'Explorer', 'Focus'],
    Gaz: ['3302', '33023', '33027'],
    Geely: ['Atlas', 'Coolray', 'Emgrand GT', 'Panda'],
    'Great Wall': ['Hover H6', 'Hover H2', 'Coolbear', 'Wingle'],
    'Great Wall HAIMA': ['Family', 'Haima 7', 'Haima 8', 'Haima S7'],
    HAVAL: ['H2', 'H6', 'H9', 'F7'],
    HINO: ['300', '500', '700', '155'],
    Honda: ['Accord', 'Civic', 'CR-V', 'Pilot'],
    Hummer: ['H1', 'H2', 'H3', 'H4'],
    Hyundai: ['Elantra', 'Santa Fe', 'Tucson', 'Palisade'],
    Infiniti: ['Q50', 'Q60', 'QX30', 'QX50'],
    Iran: ['Runna', 'Dena', 'Soren'],
    'Iran Khodro': ['Samand', 'Peugeot 405', 'Tondar 90', 'Arisun'],
    Isuzu: ['D-Max', 'MU-X', 'NHR', 'NLR'],
    Jac: ['J2', 'J4', 'J5', 'J6', 'S2', 'S3', 'S4', 'S5', 'S7', 'T6', 'X4', 'iEV7S'],
    Jaguar: ['XE', 'XF', 'XJ', 'F-PACE', 'E-PACE', 'I-PACE'],
    Jeep: ['Cherokee', 'Compass', 'Grand Cherokee', 'Renegade', 'Wrangler'],
    Kamaz: ['4350', '53605', '54901', '65201', '65222'],
    KIA: ['Ceed', 'Cerato', 'Optima', 'Rio', 'Seltos', 'Sorento', 'Sportage', 'Stinger'],
    Lada: ['Granta', 'Kalina', 'Priora', 'Vesta', 'XRAY', 'Niva'],
    'Land Rover': ['Discovery', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport'],
    Lexus: ['ES', 'GS', 'LS', 'NX', 'RX', 'UX', 'LC'],
    Lifan: ['Myway', 'X50', 'X60', 'X70', 'Solano'],
    Lincoln: ['Aviator', 'Continental', 'Corsair', 'MKC', 'MKX', 'MKZ', 'Nautilus', 'Navigator'],
    MAN: ['TGE', 'TGL', 'TGM', 'TGS', 'TGX'],
    Mazda: ['3', '6', 'CX-3', 'CX-30', 'CX-5', 'CX-8', 'MX-5'],
    'Mercedes-Benz': ['A-Class', 'B-Class', 'C-Class', 'CLA-Class', 'CLS-Class', 'E-Class', 'G-Class', 'GLA-Class', 'GLB-Class', 'GLC-Class', 'GLE-Class', 'GLS-Class', 'S-Class', 'SL-Class', 'SLS-Class', 'V-Class', 'X-Class'],
    Mini: ['Clubman', 'Countryman', 'Hatch', 'Convertible', 'Roadster', 'Coupe', 'Paceman'],
    Mitsubishi: ['ASX', 'Eclipse Cross', 'Outlander', 'Pajero', 'Pajero Sport'],
    Nissan: ['Almera', 'GT-R', 'Juke', 'Kicks', 'Leaf', 'Maxima', 'Micra', 'Murano', 'Navara', 'Note', 'Pathfinder', 'Patrol', 'Qashqai', 'Rogue', 'Sentra', 'Tiida', 'X-Trail'],
    Opel: ['Astra', 'Corsa', 'Crossland X', 'Grandland X', 'Insignia', 'Mokka X'],
    Peugeot: ['208', '2008', '301', '308', '3008', '5008', '508', 'Rifter', 'Partner', 'Traveller'],
    Pontiac: ['G8', 'Solstice', 'Vibe'],
    Porsche: ['911', 'Boxster', 'Cayenne', 'Cayman', 'Macan', 'Panamera', 'Taycan'],
    Ravon: ['Gentra', 'Nexia R3', 'R4', 'R2', 'Ravon R5'],
    Renault: ['Arkana', 'Captur', 'Clio', 'Duster', 'Fluence', 'Kadjar', 'Kaptur', 'Koleos', 'Logan'],
    Robinson: ['R22', 'R44', 'R66'],
    Rover: ['Range Rover', 'Discovery', 'Defender', 'Freelander', 'Evoque', 'Velar', 'Sport'],
    Saab: ['9-3', '9-5', '900', '9000'],
    Scania: ['S-Series', 'R-Series', 'G-Series', 'P-Series', 'L-Series'],
    Scion: ['tC', 'xA', 'xB', 'iA', 'iM'],
    Seat: ['Leon', 'Ibiza', 'Arona', 'Ateca', 'Tarraco'],
    Skoda: ['Octavia', 'Superb', 'Kodiaq', 'Karoq', 'Scala', 'Fabia'],
    Smart: ['ForTwo', 'ForFour', 'EQ ForTwo', 'Roadster'],
    'Ssang Yong': ['Tivoli', 'Korando', 'Actyon Sports', 'Rexton', 'Musso', 'XLV'],
    Subaru: ['Forester', 'Outback', 'Crosstrek', 'Impreza', 'Legacy', 'WRX', 'BRZ'],
    Suzuki: ['Swift', 'Vitara', 'Jimny', 'SX4', 'S-Cross', 'Ignis'],
    Tesla: ['Model S', 'Model X', 'Model Y', 'Model 3', 'Roadster'],
    Toyota: ['Corolla', 'Camry', 'Rav4', 'Highlander', '4Runner', 'Land Cruiser', 'Prius', 'Tacoma', 'Tundra'],
    UAZ: ['Hunter', 'Patriot', 'Bukhanka', 'Cargo', 'Profi'],
    Volkswagen: ['Golf', 'Passat', 'Jetta', 'Tiguan', 'Atlas', 'Arteon', 'Touareg'],
    Volvo: ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90'],
    Zaz: ['Sens', 'Forza', 'Chance', 'Vida', 'Slavuta', 'Lanos'],
    Zotye: ['T600', 'T700', 'T800', 'Z700', 'Z500', 'E200', 'SR8'],
    ZX: ['Admiral', 'GrandTiger', 'Landmark', 'C3 UrbanRover', 'C5 Cowboy', 'T700']
};
